server:
  port: 7780

spring:
  application:
    name: account
  cache:
    type: redis
    redis:
      time-to-live: 30s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chronos
    username: chronos
    password: chronos
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: utf8
        autoReconnect: true
        rewriteBatchedStatements: true
        zeroDateTimeBehavior: CONVERT_TO_NULL
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: chronos
    password: chronos
    virtual-host: chronos

chronos:
  snowflake-id:
    data-center-id: 1
    worker-id: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 10000
