server:
  port: 9000
spring:
  application:
    name: gateway
  cache:
    type: redis
    redis:
      time-to-live: 30s
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: storage
          uri: lb://storage
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000

management:
  endpoints:
    web:
      exposure:
        # 暴露xxx端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: "*"
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always
  server:
    port: ${random.int[7000,8000]}

chronos:
  security:
    jwt:
      expiration-time-minutes: 1440
      max-future-validity-in-minutes: 5
    excluded-uri:
      - /auth/login
      - /auth/logout
      - /actuator/health
      - /api/socket/**
      - /login
