server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://account
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  datasource:
    url: jdbc:postgresql://localhost:5432/chronos?characterEncoding=utf-8
    username: chronos
    password: chronos
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 5
        max-wait: 1000
chronos:
  security:
    excluded-uri:
      - /auth/login
      - /auth/logout
      - /actuator/health
      - /api/socket/**
      - /login
      - /auth/accounts/123
